const CHANGE_CART_TOTAL = "CHANGE_CART_TOTAL";
const DELETE_CARD = "DELETE_CARD";
const DELETE_ALL_CART = "DELETE_ALL_CART";
const GET_ALL="GET_ALL";
const GET_TOTAL_AMOUNT="GET_TOTAL_AMOUNT";

export {
    CHANGE_CART_TOTAL,
    DELETE_CARD,
    DELETE_ALL_CART,
    GET_ALL,
    GET_TOTAL_AMOUNT
}